language: python

sudo: false

cache: false

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.4
    - os: linux
      python: 3.3
    - os: linux
      python: 3.2
    - os: linux
      python: pypy3
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.5.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.4.3
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.3.6
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.2.5
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=pypy3-2.4.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin

install:
  - bash .ci/deps.${TRAVIS_OS_NAME}.sh
  - pip install pytest-cov

script:
  - python setup.py test -a "--cov=pyprint"
  - bash .ci/deploy.${TRAVIS_OS_NAME}.sh
